server:
  host: localhost
  port: 8080
  admin:
    email: admin@gmail.com
    password: 123456
database:
  host: localhost
  port: 3306
  user: root
  password: 123456
  timezone: Asia/Ho_Chi_Minh
  dbname: dev
kafka:
  bank_linking_log:
    topic: bank-linking-log
    group: bank-linking-group
    brokers:
      - localhost:9092